# Generated by Django 4.1.3 on 2023-03-01 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet', '0003_categorypet_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('eliminated_at', models.DateField(auto_now=True, verbose_name='Fecha de eliminacion')),
                ('observations', models.TextField()),
                ('medication', models.TextField()),
                ('instruction', models.TextField()),
                ('active', models.TextField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.pet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
