# Generated by Django 4.1.3 on 2023-03-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0003_alter_diagnostic_vet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
