# Generated by Django 4.1.3 on 2023-02-24 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('eliminated_at', models.DateField(auto_now=True, verbose_name='Fecha de eliminacion')),
                ('nombre', models.CharField(max_length=255, verbose_name='Pet Name Category')),
                ('descripcion', models.TextField(verbose_name='Descripcion de la categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('eliminated_at', models.DateField(auto_now=True, verbose_name='Fecha de eliminacion')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la mascota')),
                ('age', models.CharField(max_length=20, verbose_name='Edad de la mascota')),
                ('gender', models.CharField(max_length=50, verbose_name='Gender')),
                ('breed', models.CharField(max_length=150, verbose_name='Raza')),
                ('chip_number', models.CharField(max_length=10, unique=True, verbose_name='Numero de Chip')),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.categorypet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
